## 00. PyTorch Fundamentals

In [8]:
import torch
print("Hello sir")
print(torch.__version__)

Hello sir
2.9.1+cu128


In [3]:
print (torch.cuda.is_available())

True


In [6]:
!nvidia-smi # This is to run terminal code. Cool.

Thu Dec 25 18:53:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5080        On  |   00000000:01:00.0  On |                  N/A |
|  0%   45C    P1             50W /  360W |     720MiB /  16303MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Intro to Tensors

#### Creating Tensors

In [47]:
# scalar

scalar1 = torch.tensor(7) # scalar
not_a_scalar2 = torch.Tensor([7]) # not a scalar
print (scalar1)
print (not_a_scalar2)

tensor(7)
tensor([7.])


In [53]:
print (scalar1.dim()) 
print (scalar1.ndim)

print (not_a_scalar2.dim())
print (not_a_scalar2.ndim)

print (scalar1.shape)

0
0
1
1
torch.Size([])


In [49]:
print (scalar1.item())
print (not_a_scalar2.item())

7
7.0


In [50]:
#vector

vector = torch.tensor([7,7])
print (vector)

tensor([7, 7])


In [54]:
print (vector.ndim)
print (vector.dim())
print (vector.shape)

1
1
torch.Size([2])


In [62]:
#matrix

MATRIX = torch.tensor([[1,2],[3,4],[5,6]])
print (MATRIX.ndim)
print (MATRIX.shape)

2
torch.Size([3, 2])


In [63]:
print (MATRIX[0])
print (MATRIX[0].ndim)
print (MATRIX[0].shape)

print (MATRIX[1])
print (MATRIX[1].ndim)
print (MATRIX[1].shape)

print (MATRIX[2])
print (MATRIX[2].ndim)
print (MATRIX[2].shape)

tensor([1, 2])
1
torch.Size([2])
tensor([3, 4])
1
torch.Size([2])
tensor([5, 6])
1
torch.Size([2])


In [59]:
#tensor

TENSOR = torch.tensor([[[1,2],[2,3]], [[5,6],[6,7]]])
print (TENSOR)
print (TENSOR.ndim)
print (TENSOR.shape)

tensor([[[1, 2],
         [2, 3]],

        [[5, 6],
         [6, 7]]])
3
torch.Size([2, 2, 2])


In [61]:
print (TENSOR[0][0])
print (TENSOR[0][1])

tensor([1, 2])
tensor([2, 3])


#### Random Tensors

Why random tensors? Initialization before we train

In [66]:
# random tensor

random_tensor = torch.rand(3,4)
print (random_tensor)
print (random_tensor.ndim)
print (random_tensor.shape)

tensor([[3.0661e-03, 7.5585e-01, 6.5821e-04, 7.6495e-01],
        [5.7034e-02, 6.4445e-01, 1.9322e-01, 3.2415e-01],
        [9.4178e-01, 3.2853e-01, 5.8511e-01, 6.6519e-03]])
2
torch.Size([3, 4])


In [68]:
random_tensor2 = torch.rand(2,3,4,5)
print (random_tensor2)
print (random_tensor2.ndim)
print (random_tensor2.shape)

tensor([[[[0.9852, 0.0898, 0.6925, 0.9811, 0.3621],
          [0.5921, 0.5792, 0.7588, 0.7243, 0.4367],
          [0.2126, 0.3879, 0.8202, 0.8522, 0.7399],
          [0.6658, 0.2665, 0.9648, 0.0833, 0.7004]],

         [[0.8321, 0.5176, 0.5592, 0.6509, 0.2953],
          [0.9026, 0.3440, 0.7940, 0.5662, 0.4479],
          [0.8084, 0.5982, 0.2692, 0.1934, 0.7945],
          [0.3881, 0.8664, 0.3850, 0.2856, 0.8727]],

         [[0.3742, 0.2185, 0.3450, 0.0706, 0.8690],
          [0.6452, 0.5585, 0.1421, 0.8849, 0.6294],
          [0.8212, 0.6824, 0.9661, 0.7341, 0.7701],
          [0.5678, 0.7318, 0.3868, 0.4958, 0.0601]]],


        [[[0.6108, 0.0144, 0.6792, 0.2057, 0.3272],
          [0.0408, 0.0348, 0.0806, 0.0884, 0.0689],
          [0.6081, 0.1037, 0.4511, 0.4469, 0.6250],
          [0.3128, 0.0766, 0.5676, 0.4077, 0.4656]],

         [[0.0616, 0.3045, 0.0019, 0.8440, 0.2157],
          [0.8206, 0.4089, 0.6527, 0.0981, 0.5760],
          [0.7569, 0.7178, 0.9781, 0.5509, 0.7323],
  

In [82]:
# Random images

random_image_size_tensor1 = torch.rand(size=[640,480,3]) #height,width,color-channels
print (random_image_size_tensor1.shape, random_image_size_tensor1.ndim)

random_image_size_tensor2 = torch.rand(size=[3, 640,480]) #color-channels, height, width
print (random_image_size_tensor2.shape, random_image_size_tensor2.ndim)

torch.Size([640, 480, 3]) 3
torch.Size([3, 640, 480]) 3


In [83]:
#Zero tensors

zero = torch.zeros(size = (3,4)) # can use either () or []
print (zero)
print (zero.ndim, ",", zero.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2 , torch.Size([3, 4])


In [84]:
# One tensors

ones = torch.ones(size = (2,5))
print (ones)
print (ones.ndim, ",", ones.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
2 , torch.Size([2, 5])


In [85]:
#Multiplying tensors (element-wise?)

random_tensor*zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [89]:
print (random_tensor.dtype)
print (zero.dtype)
print (ones.dtype)
print (scalar1.dtype)

torch.float32
torch.float32
torch.float32
torch.int64
